// <auto-generated />
namespace project_st.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class stud_db_updating1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stud_db_updating1));
        
        string IMigrationMetadata.Id
        {
            get { return "201505251238394_stud_db_updating1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
